apps/dental_book_presenter/web/router.ex
defmodule DentalBookPresenter.Router do
  use DentalBookPresenter.Web, :router
  use Coherence.Router 

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DentalBookPresenter.PaymentStatusPlug
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true 
  end

  pipeline :zircos_layout do
    plug :put_layout, {DentalBookPresenter.ZircosLayoutView, "zircos_layout.html"}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end


  scope "/", DentalBookPresenter do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/pagamentodeplano", PaymentController, :index
    get "/redirect", PaymentController, :go_to_login_page
  end

  scope "/", DentalBookPresenter do
    pipe_through [:protected, :zircos_layout] # Use the default browser stack

    get "/login", PageController, :index
    get "/agendamentos", AttendanceController, :index
    resources "/planosdetratamento", AppointmentController do
      post "/orcamento", AppointmentController, :print_dental_invoice, as: :dental_invoice
    end
    resources "/pacientes", PatientController do
      get "/anamnese", PatientController, :new_anamnesis, as: :anamnesis
      get "/anamneserespondida/:anamnesis_id", PatientController, :show_anamnesis, as: :anamnesis
      post "/anamnese", PatientController, :save_anamnesis, as: :anamnesis
      post "/emitiranamnese", PatientController, :print_anamnesis, as: :anamnesis
      get "/atestado", SickNoteController, :index
      get "/visualizaratestado", SickNoteController, :show_sick_note
      post "/atestado", SickNoteController, :create_sick_note
      get "/receituario", PrescriptionController, :index
      get "/visualizarreceituario", PrescriptionController, :show_prescription
      post "/receituario", PrescriptionController, :create_prescription
    end
    resources "/procedimentos", ProcedureController
    resources "/receitas", IncomeController
    resources "/despesas", ExpenseController
    resources "/colaboradores", TeamController
    resources "/modelodeatestado", SickNoteTemplateController
    resources "/medicamentos", MedicineController
    get "/fluxodecaixa", FinancialController, :index
    post "/fluxodecaixa", FinancialController, :get_custom_financial
    get "/obtemPacientes", PatientController, :get_patients
    get "/obtemProcedimentos", ProcedureController, :get_procedures
    get "/obtemProfissionaisDeSaude", TeamController, :get_dentists
    get "/receitasporprocedimentos", GroupedIncomeController, :index
    post "/receitasporprocedimentosfiltrados", GroupedIncomeController, :filter
    get "/filtramedicamentos", MedicineController, :get_medicines
   end

  # Other scopes may use custom stacks.
  scope "/api", DentalBookPresenter do
    pipe_through :api

    post "/confirmarassinatura", PaymentController, :signature_confirmation
    post "/atualizarassinatura", PaymentController, :signature_update
  end
end

apps/dental_book_presenter/web/controllers/patient_controller.ex
defmodule DentalBookPresenter.PatientController do
  use DentalBookPresenter.Web, :controller
  use Rummage.Phoenix.Controller

  alias DentalBookPresenter.Patient
  alias DentalBookPresenter.Tenant
  alias DentalBookPresenter.RummageConfig
  alias DentalBookPresenter.PatientUI
  alias DentalBookPresenter.Appointment
  alias DentalBookPresenter.PatientRepo
  alias DentalBookPresenter.PatientClinicalHistory
  alias DentalBookPresenter.PatientFinancialHistory
  alias DentalBookPresenter.Anamnesis
  alias DentalBookPresenter.ReportGenerator
  alias DentalBookPresenter.DateFormat

  def index(conn, params) do
    user_id = conn.assigns.current_user.id

    results_per_page = "5"
    rummage_default =  RummageConfig.get_default_params_from(params, results_per_page)

    {query_paginated, rummage} = 
    RummageConfig.get_rummage_query_with_tenant_name(Patient, user_id)
    |> Rummage.Ecto.rummage(rummage_default)

    patients = Apartmentex.all(Repo, query_paginated, Tenant.get_name(user_id, Repo))
    |> PatientUI.get_patient_ui_from

    render(conn, "index.html", patients: patients, rummage: rummage)
  end

  def new(conn, _params) do
    changeset = PatientUI.changeset(%PatientUI{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"patient_ui" => patient_params}) do
    changeset = Patient.changeset(%Patient{}, patient_params)
    user_id = conn.assigns.current_user.id

    case Apartmentex.insert(Repo, changeset, Tenant.get_name(user_id, Repo)) do
      {:ok, _patient} ->
        conn
        |> put_flash(:info, "Paciente criado com sucesso.")
        |> redirect(to: patient_path(conn, :index))
      {:error, changeset} ->
        patient_ui_changeset = PatientUI.changeset(%PatientUI{}, patient_params)
        |> Map.put(:action, changeset.action)
        |> Map.put(:errors, changeset.errors)
        render(conn, "new.html", changeset: patient_ui_changeset)
    end
  end

  def show(conn, %{"id" => patient_id}) do
    user_id = conn.assigns.current_user.id

    patient = Apartmentex.get!(Repo, Patient, patient_id, Tenant.get_name(user_id, Repo))

    raw_patient_history = PatientRepo.get_history_of(patient_id, user_id)

    clinical_history = PatientClinicalHistory.get_data_in(raw_patient_history)
    financial_history = PatientFinancialHistory.get_data_in(raw_patient_history)
    anamnesis_history = PatientRepo.get_anamnesis_history(patient_id, user_id)
    sick_notes_history = PatientRepo.get_sick_notes_history(patient_id, user_id)
    prescriptions_history = PatientRepo.get_prescriptions_history(patient_id, user_id)

    patient_history = %{
      clinical_history: clinical_history,
      financial_history: financial_history,
      anamnesis_history: anamnesis_history,
      sick_notes_history: sick_notes_history,
      prescriptions_history: prescriptions_history
    }

    render(conn, "show.html", patient: patient, patient_history: patient_history)
  end

  def edit(conn, %{"id" => id}) do
    user_id = conn.assigns.current_user.id

    patient = Apartmentex.get!(Repo, Patient, id, Tenant.get_name(user_id, Repo))
    |> PatientUI.get_patient_ui_from

    changeset = PatientUI.changeset(patient)
    render(conn, "edit.html", patient: patient, changeset: changeset)
  end

  def update(conn, %{"id" => id, "patient_ui" => patient_params}) do
    user_id = conn.assigns.current_user.id
    patient = Apartmentex.get!(Repo, Patient, id, Tenant.get_name(user_id, Repo))
    changeset = Patient.changeset(patient, patient_params)

    case Apartmentex.update(Repo, changeset, Tenant.get_name(user_id, Repo)) do
      {:ok, _patient} ->
        conn
        |> put_flash(:info, "Paciente atualizado com sucesso.")
        |> redirect(to: patient_path(conn, :index))
      {:error, changeset} ->
        patient_ui_changeset = PatientUI.changeset(%PatientUI{}, patient_params)
        |> Map.put(:action, changeset.action)
        |> Map.put(:errors, changeset.errors)
        render(conn, "edit.html", patient: patient, changeset: patient_ui_changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user_id = conn.assigns.current_user.id
    
    Apartmentex.all(Repo, search_patient_by(id), Tenant.get_name(user_id, Repo))
    |> patient_to_be_deleted(conn, user_id)
  end

  defp patient_to_be_deleted([], conn, _user_id) do
    conn
    |> put_flash(:error, "Paciente não pode ser excluído pois já está vinculado a um plano de tratamento.")
    |> redirect(to: patient_path(conn, :index))
  end

  defp patient_to_be_deleted([%Patient{}] = patients, conn, user_id) do
    first_position = 0
    {:ok, patient} = patients |> Enum.fetch(first_position)

    Apartmentex.delete(Repo, patient, Tenant.get_name(user_id, Repo))

    conn
    |> put_flash(:info, "Paciente excluído com sucesso.")
    |> redirect(to: patient_path(conn, :index))
  end

  def search_patient_by(patient_id) do
    from p in Patient,
    left_join: a in Appointment, 
    on: p.id == a.patient_id, 
    where: p.id == ^patient_id
    and is_nil(a.patient_id),
    select: p
  end

  def get_patients(conn, %{"query" => query}) do
    user_id = conn.assigns.current_user.id
    patients = search_patients(user_id, query)

    patients_map = Enum.map(patients, fn patient -> %{label_of_patient_name: "<b>#{patient.name}</b>", 
                                                   patient_name: patient.name, 
                                                   patient_cellphone: patient.cellphone, 
                                                   patient_id: patient.id} 
                                                   end)

    json conn, patients_map
  end

  def new_anamnesis(conn, %{"patient_id" => patient_id}) do
    user_id = conn.assigns.current_user.id
    patient = Apartmentex.get!(Repo, Patient, patient_id, Tenant.get_name(user_id, Repo))
    changeset = Anamnesis.changeset(%Anamnesis{})
    render(conn, "anamnesis.html", changeset: changeset, patient: patient)
  end

  def save_anamnesis(conn, %{"patient_id" => patient_id, "anamnesis" => anamnesis} ) do
    user_id = conn.assigns.current_user.id
    anamnesis_responses = %{responses: anamnesis}
    changeset = Anamnesis.changeset(%Anamnesis{}, anamnesis_responses)
    saved_anamnesis = Apartmentex.insert!(Repo, changeset, Tenant.get_name(user_id, Repo))
    patient = Apartmentex.get!(Repo, Patient, patient_id, Tenant.get_name(user_id, Repo))
    render(conn, "show_anamnesis.html", patient: patient, answered_anamnesis: saved_anamnesis, conn: conn)
  end

  def show_anamnesis(conn, %{"patient_id" => patient_id, "anamnesis_id" => anamnesis_id}) do
    user_id = conn.assigns.current_user.id
    patient = Apartmentex.get!(Repo, Patient, patient_id, Tenant.get_name(user_id, Repo))
    answered_anamnesis = PatientRepo.get_answered_anamnesis(anamnesis_id, user_id)

    render(conn, "show_anamnesis.html", patient: patient, answered_anamnesis: answered_anamnesis, conn: conn)
  end

  def print_anamnesis(conn, %{"patient_id" => patient_id, "params" => params}) do
    user_id = conn.assigns.current_user.id

    anamnesis_id = extract_values_of_query_string_from(params)
    patient = Apartmentex.get!(Repo, Patient, patient_id, Tenant.get_name(user_id, Repo))
    answered_anamnesis = PatientRepo.get_answered_anamnesis(anamnesis_id, user_id)

    template_params = get_template_params(patient, answered_anamnesis)

    anamnesis_file_params = [file_name: "anamnese", template_path: get_template_path(), template_params: template_params]
    
    {filename, pdf_content} = ReportGenerator.create_pdf(anamnesis_file_params)

    conn
    |> put_resp_content_type("application/pdf")
    |> put_resp_header("content-disposition", "attachment; filename=#{filename}")
    |> send_resp(200, pdf_content)
  end

  defp search_patients(user_id, search_term) do
     query = from p in Patient, 
     where: ilike(p.name, ^search_term),
     or_where: ilike(p.cellphone, ^search_term),
     select: %{id: p.id, name: p.name, cellphone: p.cellphone}
     
     Apartmentex.all(Repo, query, Tenant.get_name(user_id, Repo))
  end

  defp extract_values_of_query_string_from(params) do
    find_everything_till_equal_sign = ~r/.+?=/
    params 
    |> String.replace("&", "") 
    |> String.replace(find_everything_till_equal_sign, "")
  end
  defp get_template_path(), do: "/templates/dental_anamnesis/anamnesis_report.html.eex"

  defp get_template_params(patient, answered_anamnesis) do
    [
      answered_anamnesis: answered_anamnesis, 
      patient: patient, 
      phoenix_view: Phoenix.View, 
      patient_view: DentalBookPresenter.PatientView, 
      phoenix_html: Phoenix.HTML,
      emission_date: DateFormat.now() |> DateFormat.ecto_date_to_string,
      creation_date: answered_anamnesis.inserted_at |> DateFormat.naive_date_to_ecto_date |> DateFormat.ecto_date_to_string
    ]
  end

end

apps/dental_book_presenter/web/views/patient/history_nav_view.ex
defmodule DentalBookPresenter.HistoryNavView do
  use DentalBookPresenter.Web, :view

  def create_tab(href, aria_expanded, title, class \\ "") do
    content_tag :li, class: class do
      content_tag :a, href: href, data: [toggle: "tab"], aria: [expanded: aria_expanded] do
      [
        content_tag(:span, content_tag(:i, "", class: "fa fa-home"), class: "visible-xs"),
        content_tag(:span, title, class: "hidden-xs")
      ]
      end
    end
  end

  def create_nav_buttons(:history) do
    procedure_button = create_button("Procedimentos", "btn-all-procedures-history")
    anamnesis_button = create_button("Anamneses", "btn-all-anamnesis-history")
    sick_notes_button = create_button("Atestados", "btn-all-sick-notes-history")
    prescriptions_button = create_button("Receituários", "btn-all-prescriptions-history")

    [procedure_button, anamnesis_button, sick_notes_button, prescriptions_button]
    |> group
  end

  def create_nav_buttons(:financial) do
    all_bills_button = create_button("Geral", "btn-all-summated-bills")
    paid_bills = create_button("Pagas", "btn-paid-bills")
    unpaid_not_overdue = create_button("A pagar", "btn-unpaid-not-overdue")
    unpaid_overdue = create_button("Em atraso", "btn-unpaid-overdue")

    [all_bills_button, paid_bills, unpaid_not_overdue, unpaid_overdue]
    |> group
  end

  defp create_button(label, id) do
    content_tag :a, id: id, class: "btn btn-default waves-effect", role: "button" do
      label        
    end
  end

  defp group(buttons) do
    content_tag :div, class: "btn-group btn-group-justified m-b-10" do
      buttons
    end
  end
end

apps/dental_book_presenter/web/views/patient/patient_view.ex
defmodule DentalBookPresenter.PatientView do
  use DentalBookPresenter.Web, :view
  use Rummage.Phoenix.View
  alias DentalBookPresenter.HistoryNavView
  alias DentalBookPresenter.HistoryTimelineView
  alias DentalBookPresenter.FinancialHistoryView
  alias DentalBookPresenter.AnamnesisView
  alias DentalBookPresenter.ShowingAnamnesisView
  alias DentalBookPresenter.PageTitle

  def create_date_picker(form, field) do
    content_tag :div, class: "input-group" do
      text_input(form, field, class: "form-control patient_birth_date", placeholder: "dd/mm/aaaa")
    end
  end

  def get_hidden_default_age_from(patient_age) do
    patient_age
    |> Kernel.inspect
    |> String.replace("anos", "") 
    |> String.replace("\"", "") 
    |> String.trim
  end
  
  def get_patient_name_from(patient_history) do
    history_item = List.first(patient_history)
    get_name_in(history_item)    
  end

  def create_tab(href, aria_expanded, title, class \\ ""), do: HistoryNavView.create_tab(href, aria_expanded, title, class)
  def create_nav_buttons(of_this_component), do: HistoryNavView.create_nav_buttons(of_this_component)
  def create_timeline_with(procedure_history, patient, conn), do: HistoryTimelineView.create(:procedures, procedure_history, patient, conn)
  def create_timeline_with_anamnesis(anamnesis_history, patient, conn), do: HistoryTimelineView.create(:anamnesis, anamnesis_history, patient, conn)
  def create_timeline_with_sick_notes(sick_notes_history, patient, conn), do: HistoryTimelineView.create(:sick_notes, sick_notes_history, patient, conn)
  def create_timeline_with_prescriptions(prescriptions_history, patient, conn), do: HistoryTimelineView.create(:prescriptions, prescriptions_history, patient, conn)
  def create_patient_avatar(), do: FinancialHistoryView.create_patient_avatar()
  def create_identifiers_of(patient), do: FinancialHistoryView.create_identifiers_of(patient)
  def create_button_to(path_to_go, patient, conn), do: FinancialHistoryView.create_button_to(path_to_go, patient, conn)
  def create_details_of(patient), do: FinancialHistoryView.create_details_of(patient)
  def create_financial_general_resume(patient_history), do: FinancialHistoryView.create_financial_general_resume(patient_history)
  def create_financial_table_of(table_type, financial_history, conn), do: FinancialHistoryView.create_financial_table_of(table_type, financial_history, conn)
  def create_question(question_description, question_type, input_name, explanation_description \\ "") do
    AnamnesisView.create_question(question_description, question_type, input_name, explanation_description)
  end

  def show_question(with_this_name, from_this_map), do: ShowingAnamnesisView.show_question(with_this_name, from_this_map)

  def get_label_from(action_type), do: PageTitle.get_label_from(action_type)

  defdelegate not_exists?(patients), to: DentalBookPresenter.OnboardValidation
  defdelegate get_title(), to: DentalBookPresenter.OnboardMessages
  defdelegate get_use_instructions(), to: DentalBookPresenter.OnboardMessages, as: :get_patient_instructions
  defdelegate get_patient_history_instructions(), to: DentalBookPresenter.OnboardMessages
  defdelegate get_icon_type(), to: DentalBookPresenter.OnboardMessages

  def show_that_patient_list_is_empty() do
    content_tag :div, style: "text-align:center" do
    [
      content_tag(:div,"", class: "swal-icon swal-icon--info"),
      content_tag(:div, "Ainda não existem pacientes cadastrados", class: "swal-title"),
      content_tag(:div, "Mais informações no botão \"Instruções de uso\".", class: "swal-text")
    ]
    end
  end

  defp get_name_in(history_item) when is_nil(history_item), do: "Paciente não possui histórico"
  defp get_name_in(history_item) do
    history_item.patient_name
  end
end

apps/dental_book_presenter/web/templates/patient/anamnesis.html.eex
<div class="content-page">
    <div class="content">
        <div class="container">

          <div class="row">
            <div class="col-xs-12">
              <div class="page-title-box">
                  <h4 class="page-title">Anamnese</h4>
                  <div class="clearfix"></div>
              </div>
            </div>
          </div>

          <div class="card-box">
            
             <h3 class=" m-t-0 m-b-30"><%= @patient.name %></h3>
             <%= form_for @changeset, patient_anamnesis_path(@conn, :save_anamnesis, @patient), fn f -> %>
                <input type="hidden" name="anamnesis[patient_id]" value="<%= @patient.id %>"/>

                <%= create_question("Qual sua queixa principal?", :free_text, "principal_issue") %>
                <%= create_question("Sofre de alguma doença?", :single_choice_with_free_text, "has_any_desease", "Em caso positivo, quais?") %>
                <%= create_question("Está gestante?", :single_choice, "is_pregnant") %>
                <%= create_question("Está em tratamento médico atualmente?", :single_choice, "is_in_treatment") %>
                <%= create_question("Está fazendo uso de alguma medicação?", :single_choice_with_free_text, "under_medication", "Em caso positivo, quais?") %>
                <%= create_question("Já foi operado?", :single_choice_with_free_text, "did_surgery", "Em caso positivo, por que?") %>
                <%= create_question("Teve problemas com a cicatrização?", :single_choice, "had_cicatrization_issues") %>
                <%= create_question("Teve problemas com a anestesia?", :single_choice, "had_anesthetic_issues") %>
                <%= create_question("Teve problemas de hemorragia?", :single_choice, "had_bleeding_issues") %>
                <%= create_question("Sofre de problemas articulares ou reumatismo?", :single_choice, "had_joints_issues") %>
                <%= create_question("Sofre de febre reumática?", :single_choice, "had_reumathic_fever") %>
                <%= create_question("Sofre de problemas cardíacos?", :single_choice, "had_heart_issues") %>
                <%= create_question("Sofre de problemas renais?", :single_choice, "had_kidney_issues") %>
                <%= create_question("Sofre de problemas gástricos?", :single_choice, "had_gastric_issues") %>
                <%= create_question("Sofre de problemas respiratórios?", :single_choice, "had_breathing_issues") %>
                <%= create_question("Sofre de problemas alérgicos?", :single_choice_with_free_text, "had_alergic_issues", "Em caso positivo, quais?") %>
                <%= create_question("Sofre de diabetes?", :single_choice, "had_diabetes_issues") %>
                <%= create_question("Sofre de hipertensão arterial?", :single_choice, "had_arterial_hypertesion") %>
                <%= create_question("Antecedentes familiares", :free_text, "familiar_background") %>
                <%= create_question("Outras observações importantes", :free_text, "others_observations") %>
                
                <div class="text-right panel-footer m-t-20">
                    <%= link "Cancelar", to: patient_path(@conn, :show, @patient), class: "btn" %>
                    <%= submit "Salvar", class: "btn btn-info" %>
                </div>
             <% end %>
          </div> <!-- card -->

        </div> <!-- container -->
    </div> <!-- content -->
</div> <!-- content page -->

apps/dental_book_presenter/web/templates/patient/edit.html.eex
<%= render "form.html", changeset: @changeset,
                        action: patient_path(@conn, :update, @patient),
                        conn: @conn,
                        method: :put,
                        patient_age: @patient.age,
                        action_type: :edit %>

apps/dental_book_presenter/web/templates/patient/new.html.eex
<%= render "form.html", changeset: @changeset,
                        action: patient_path(@conn, :create),
                        conn: @conn,
                        method: :post,
                        patient_age: "0",
                        action_type: :new %>

apps/dental_book_presenter/web/templates/patient/show_anamnesis.html.eex
<div class="content-page">
    <div class="content">
        <div class="container">

          <div class="row">
            <div class="col-xs-12">
              <div class="page-title-box">
                  <h4 class="page-title">Anamnese</h4>
                  <div class="clearfix"></div>
              </div>
            </div>
          </div>

          <div class="btn-group m-b-10 m-l-5">
            <%= link "Emitir anamnese", to: "#", id: "anamnesisButton", class: "btn btn-lg btn-success waves-effect" %>
          </div>

          <div class="card-box">
            <h1><%= @patient.name %></h1>
            <hr>
            <%= render DentalBookPresenter.PatientView, "show_anamnesis_content.html", anamnesis: @answered_anamnesis %>
          </div> <!-- card -->
         

    </div> <!-- container -->
  </div> <!-- content -->
</div> <!-- content page -->


<script>
    var anamnesisButton = document.getElementById("anamnesisButton"); 
    anamnesisButton.addEventListener("click", printAnamnesis, false);
   
    function printAnamnesis(){
      var http = new XMLHttpRequest();
      var url = "<%= patient_anamnesis_path(@conn, :print_anamnesis, @patient) %>";
      var csrf_token = <%= raw Poison.encode!(Plug.CSRFProtection.get_csrf_token()) %>;
      var params = "params=" + getAnamnesisParams();
      
      http.open("POST", url, true);
      http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
      http.setRequestHeader("X-CSRF-Token", csrf_token);
      http.responseType = 'arraybuffer';

      http.onreadystatechange = function() {
        var success = 200;
        var report_name = "anamnese.pdf";
        if(http.readyState == XMLHttpRequest.DONE && http.status == success) {
            var blob = new Blob([http.response], {type: "application/pdf"});

            if (window.navigator && window.navigator.msSaveOrOpenBlob) {
              window.navigator.msSaveOrOpenBlob(blob, report_name);
              return;
            } 

            var file = window.URL.createObjectURL(blob);
            var link = document.createElement("a");
            link.href = file;   
            link.download = report_name;   
            document.body.appendChild(link);
            link.click();
        }
      }

      http.send(params);
    }

    function getAnamnesisParams(){
      var anamnesisId = <%= @answered_anamnesis.id %>;
      return escape(`&anamnesis_id=${anamnesisId}`);
    }
</script>

apps/dental_book_presenter/web/templates/patient/show_anamnesis_content.html.eex
<style>
    section{
        margin-bottom: 30px;
    }
</style>

<%= show_question("principal_issue", @anamnesis) %>
<%= show_question("has_any_desease", @anamnesis) %>
<%= show_question("is_pregnant", @anamnesis) %>
<%= show_question("is_in_treatment", @anamnesis) %>
<%= show_question("under_medication", @anamnesis) %>
<%= show_question("did_surgery", @anamnesis) %>
<%= show_question("had_cicatrization_issues", @anamnesis) %>
<%= show_question("had_anesthetic_issues", @anamnesis) %>
<%= show_question("had_bleeding_issues", @anamnesis) %>
<%= show_question("had_joints_issues", @anamnesis) %>
<%= show_question("had_reumathic_fever", @anamnesis) %>
<%= show_question("had_heart_issues", @anamnesis) %>
<%= show_question("had_kidney_issues", @anamnesis) %>
<%= show_question("had_gastric_issues", @anamnesis) %>
<%= show_question("had_alergic_issues", @anamnesis) %>
<%= show_question("had_diabetes_issues", @anamnesis) %>
<%= show_question("had_arterial_hypertesion", @anamnesis) %>
<%= show_question("familiar_background", @anamnesis) %>
<%= show_question("others_observations", @anamnesis) %>